version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: 7BkTuGmikCga9dcNvdy9sw==
  DOCKER_PASS:
    secure: o3eE7YJ2gi4hP5bJClZFIQ==

install:
  - ps: docker version

build_script:
  - ps: docker build -t metasyn/nim-servercore .

test_script:
  - ps: docker run metasyn/nim-servercore "nim.exe --version"
  - ps: docker run metasyn/nim-servercore "nimble.exe --version"

deploy_script:
  - ps: echo $env:DOCKER_PASS | docker login -u="$env:DOCKER_USER" --password-stdin
  - ps: docker push metasyn/nim-servercore
